//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeViewer.Communication.EmployeeViewerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeViewerService.EmployeeViewerServiceSoap")]
    public interface EmployeeViewerServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        int AddEmployee(EmployeeViewer.Communication.EmployeeViewerService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddEmployeeAsync(EmployeeViewer.Communication.EmployeeViewerService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        int RemoveEmployee(EmployeeViewer.Communication.EmployeeViewerService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RemoveEmployeeAsync(EmployeeViewer.Communication.EmployeeViewerService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        int UpdateEmployee(EmployeeViewer.Communication.EmployeeViewerService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateEmployeeAsync(EmployeeViewer.Communication.EmployeeViewerService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDepartment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        int AddDepartment(EmployeeViewer.Communication.EmployeeViewerService.Department department);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDepartment", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddDepartmentAsync(EmployeeViewer.Communication.EmployeeViewerService.Department department);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveDepartment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        int RemoveDepartment(EmployeeViewer.Communication.EmployeeViewerService.Department department);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveDepartment", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RemoveDepartmentAsync(EmployeeViewer.Communication.EmployeeViewerService.Department department);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDepartment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        int UpdateDepartment(EmployeeViewer.Communication.EmployeeViewerService.Department department);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDepartment", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateDepartmentAsync(EmployeeViewer.Communication.EmployeeViewerService.Department department);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        EmployeeViewer.Communication.EmployeeViewerService.Department[] GetDepartments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartments", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeViewer.Communication.EmployeeViewerService.Department[]> GetDepartmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        EmployeeViewer.Communication.EmployeeViewerService.Employee[] GetEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeViewer.Communication.EmployeeViewerService.Employee[]> GetEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        EmployeeViewer.Communication.EmployeeViewerService.Employee GetEmployee(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeViewer.Communication.EmployeeViewerService.Employee> GetEmployeeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        EmployeeViewer.Communication.EmployeeViewerService.Employee[] FindEmployee(EmployeeViewer.Communication.EmployeeViewerService.Employee pattern);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeViewer.Communication.EmployeeViewerService.Employee[]> FindEmployeeAsync(EmployeeViewer.Communication.EmployeeViewerService.Employee pattern);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        EmployeeViewer.Communication.EmployeeViewerService.Department GetDepartment(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartment", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeViewer.Communication.EmployeeViewerService.Department> GetDepartmentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindDepartment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        EmployeeViewer.Communication.EmployeeViewerService.Department[] FindDepartment(EmployeeViewer.Communication.EmployeeViewerService.Department pattern);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindDepartment", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeViewer.Communication.EmployeeViewerService.Department[]> FindDepartmentAsync(EmployeeViewer.Communication.EmployeeViewerService.Department pattern);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Employee : Entity {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string middleNameField;
        
        private int ageField;
        
        private Gender genderField;
        
        private Department departmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
                this.RaisePropertyChanged("MiddleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
                this.RaisePropertyChanged("Age");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Gender Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Department Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("Department");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum Gender {
        
        /// <remarks/>
        Male,
        
        /// <remarks/>
        Female,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Department : Entity {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Department))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employee))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Entity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeViewerServiceSoapChannel : EmployeeViewer.Communication.EmployeeViewerService.EmployeeViewerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeViewerServiceSoapClient : System.ServiceModel.ClientBase<EmployeeViewer.Communication.EmployeeViewerService.EmployeeViewerServiceSoap>, EmployeeViewer.Communication.EmployeeViewerService.EmployeeViewerServiceSoap {
        
        public EmployeeViewerServiceSoapClient() {
        }
        
        public EmployeeViewerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeViewerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeViewerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeViewerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddEmployee(EmployeeViewer.Communication.EmployeeViewerService.Employee employee) {
            return base.Channel.AddEmployee(employee);
        }
        
        public System.Threading.Tasks.Task<int> AddEmployeeAsync(EmployeeViewer.Communication.EmployeeViewerService.Employee employee) {
            return base.Channel.AddEmployeeAsync(employee);
        }
        
        public int RemoveEmployee(EmployeeViewer.Communication.EmployeeViewerService.Employee employee) {
            return base.Channel.RemoveEmployee(employee);
        }
        
        public System.Threading.Tasks.Task<int> RemoveEmployeeAsync(EmployeeViewer.Communication.EmployeeViewerService.Employee employee) {
            return base.Channel.RemoveEmployeeAsync(employee);
        }
        
        public int UpdateEmployee(EmployeeViewer.Communication.EmployeeViewerService.Employee employee) {
            return base.Channel.UpdateEmployee(employee);
        }
        
        public System.Threading.Tasks.Task<int> UpdateEmployeeAsync(EmployeeViewer.Communication.EmployeeViewerService.Employee employee) {
            return base.Channel.UpdateEmployeeAsync(employee);
        }
        
        public int AddDepartment(EmployeeViewer.Communication.EmployeeViewerService.Department department) {
            return base.Channel.AddDepartment(department);
        }
        
        public System.Threading.Tasks.Task<int> AddDepartmentAsync(EmployeeViewer.Communication.EmployeeViewerService.Department department) {
            return base.Channel.AddDepartmentAsync(department);
        }
        
        public int RemoveDepartment(EmployeeViewer.Communication.EmployeeViewerService.Department department) {
            return base.Channel.RemoveDepartment(department);
        }
        
        public System.Threading.Tasks.Task<int> RemoveDepartmentAsync(EmployeeViewer.Communication.EmployeeViewerService.Department department) {
            return base.Channel.RemoveDepartmentAsync(department);
        }
        
        public int UpdateDepartment(EmployeeViewer.Communication.EmployeeViewerService.Department department) {
            return base.Channel.UpdateDepartment(department);
        }
        
        public System.Threading.Tasks.Task<int> UpdateDepartmentAsync(EmployeeViewer.Communication.EmployeeViewerService.Department department) {
            return base.Channel.UpdateDepartmentAsync(department);
        }
        
        public EmployeeViewer.Communication.EmployeeViewerService.Department[] GetDepartments() {
            return base.Channel.GetDepartments();
        }
        
        public System.Threading.Tasks.Task<EmployeeViewer.Communication.EmployeeViewerService.Department[]> GetDepartmentsAsync() {
            return base.Channel.GetDepartmentsAsync();
        }
        
        public EmployeeViewer.Communication.EmployeeViewerService.Employee[] GetEmployees() {
            return base.Channel.GetEmployees();
        }
        
        public System.Threading.Tasks.Task<EmployeeViewer.Communication.EmployeeViewerService.Employee[]> GetEmployeesAsync() {
            return base.Channel.GetEmployeesAsync();
        }
        
        public EmployeeViewer.Communication.EmployeeViewerService.Employee GetEmployee(int id) {
            return base.Channel.GetEmployee(id);
        }
        
        public System.Threading.Tasks.Task<EmployeeViewer.Communication.EmployeeViewerService.Employee> GetEmployeeAsync(int id) {
            return base.Channel.GetEmployeeAsync(id);
        }
        
        public EmployeeViewer.Communication.EmployeeViewerService.Employee[] FindEmployee(EmployeeViewer.Communication.EmployeeViewerService.Employee pattern) {
            return base.Channel.FindEmployee(pattern);
        }
        
        public System.Threading.Tasks.Task<EmployeeViewer.Communication.EmployeeViewerService.Employee[]> FindEmployeeAsync(EmployeeViewer.Communication.EmployeeViewerService.Employee pattern) {
            return base.Channel.FindEmployeeAsync(pattern);
        }
        
        public EmployeeViewer.Communication.EmployeeViewerService.Department GetDepartment(int id) {
            return base.Channel.GetDepartment(id);
        }
        
        public System.Threading.Tasks.Task<EmployeeViewer.Communication.EmployeeViewerService.Department> GetDepartmentAsync(int id) {
            return base.Channel.GetDepartmentAsync(id);
        }
        
        public EmployeeViewer.Communication.EmployeeViewerService.Department[] FindDepartment(EmployeeViewer.Communication.EmployeeViewerService.Department pattern) {
            return base.Channel.FindDepartment(pattern);
        }
        
        public System.Threading.Tasks.Task<EmployeeViewer.Communication.EmployeeViewerService.Department[]> FindDepartmentAsync(EmployeeViewer.Communication.EmployeeViewerService.Department pattern) {
            return base.Channel.FindDepartmentAsync(pattern);
        }
    }
}
